// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KeyMappingTestProject
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidKeyMappingTestProjectPackageString = "e710e1f5-7abb-4604-bd93-5ec687b1ed1e";
        public static Guid guidKeyMappingTestProjectPackage = new Guid(guidKeyMappingTestProjectPackageString);

        public const string guidKeyMappingTestProjectPackageCmdSetString = "50ba3da8-a2ff-483d-a880-7b913edcf803";
        public static Guid guidKeyMappingTestProjectPackageCmdSet = new Guid(guidKeyMappingTestProjectPackageCmdSetString);

        public const string guidImagesString = "6c732d6f-0bdd-4dd6-8ba6-c52490fcbae3";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Command1Id = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}